<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        
        $vehicles = [
            [
                'brand' => 'Audi',
                'model' => 'A1',
                'year' => 2021,
                'color' => 'Gris',
                'fuel' => 'Gasolina',
                'transmission' => 'Manual',
                'price' => 45.00,
                'type' => 'Compacto',
                'image_1' => 'vehicles-photos/AUDI_A1.png',
                'description' => 'Compacto ágil y eficiente, ideal para la ciudad.',
                'fee' => 150,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'BMW',
                'model' => 'M135',
                'year' => 2023,
                'color' => 'Gris',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 75.00,
                'type' => 'Sedán',
                'image_1' => 'vehicles-photos/BMW_M135.png',
                'description' => 'Elegancia y rendimiento en un sedán de lujo.',
                'fee' => 200,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Audi',
                'model' => 'Q5',
                'year' => 2022,
                'color' => 'Gris',
                'fuel' => 'Diésel',
                'transmission' => 'Automático',
                'price' => 89.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/AUDI_Q5.png',
                'description' => 'SUV con estilo deportivo y excelente comportamiento en carretera.',
                'fee' => 270,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Audi',
                'model' => 'Q7',
                'year' => 2023,
                'color' => 'Negro',
                'fuel' => 'Diésel',
                'transmission' => 'Automático',
                'price' => 95.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/AUDI_Q7.png',
                'description' => 'SUV de lujo con gran capacidad, ideal para familias o largas distancias.',
                'fee' => 290,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'BMW',
                'model' => 'iX1',
                'year' => 2023,
                'color' => 'Blanco',
                'fuel' => 'Eléctrico',
                'transmission' => 'Automático',
                'price' => 88.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/BMW_iX1.png',
                'description' => 'SUV eléctrico compacto con gran eficiencia y tecnología de punta.',
                'fee' => 265,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'BMW',
                'model' => 'Serie 1',
                'year' => 2021,
                'color' => 'Blanco',
                'fuel' => 'Gasolina',
                'transmission' => 'Manual',
                'price' => 58.00,
                'type' => 'Compacto',
                'image_1' => 'vehicles-photos/BMW_SERIE_1.png',
                'description' => 'Compacto premium ideal para ciudad y viajes rápidos.',
                'fee' => 170,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'BMW',
                'model' => 'Serie 2',
                'year' => 2022,
                'color' => 'Gris',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 65.00,
                'type' => 'Sedán',
                'image_1' => 'vehicles-photos/BMW_SERIE_2.png',
                'description' => 'Sedán deportivo con alto rendimiento y confort.',
                'fee' => 195,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'BMW',
                'model' => 'Serie 3',
                'year' => 2021,
                'color' => 'Negro',
                'fuel' => 'Diésel',
                'transmission' => 'Automático',
                'price' => 75.00,
                'type' => 'Sedán',
                'image_1' => 'vehicles-photos/BMW_SERIE_3.png',
                'description' => 'El clásico sedán de BMW con equilibrio entre lujo y deportividad.',
                'fee' => 230,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'BMW',
                'model' => 'X1',
                'year' => 2022,
                'color' => 'Blanco',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 72.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/BMW_X1.png',
                'description' => 'SUV compacto con espacio y confort para el día a día.',
                'fee' => 215,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'BMW',
                'model' => 'BMW_X4_M',
                'year' => 2023,
                'color' => 'Blanco Polar',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 105.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/BMW_X4_M.png',
                'description' => 'SUV M de alta gama, ideal para ciudad y carretera.',
                'fee' => 320,
                'typeWarranty' => 'Exclusive',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Citroën',
                'model' => 'Berlingo',
                'year' => 2021,
                'color' => 'Gris oscuro',
                'fuel' => 'Diésel',
                'transmission' => 'Manual',
                'price' => 55.00,
                'type' => 'Familiar',
                'image_1' => 'vehicles-photos/CITROEN_BERLINGO.png',
                'description' => 'Vehículo versátil y espacioso, ideal para familias o transporte comercial.',
                               'fee' => 165,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Citroën',
                'model' => 'Berlingo XL',
                'year' => 2022,
                'color' => 'Verde oliva',
                'fuel' => 'Diésel',
                'transmission' => 'Manual',
                'price' => 60.00,
                'type' => 'Familiar',
                'image_1' => 'vehicles-photos/CITROEN_BERLINGO_XL.png',
                'description' => 'Versión XL con mayor capacidad de carga y comodidad.',
                'fee' => 180,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Citroën',
                'model' => 'C3',
                'year' => 2020,
                'color' => 'Blanco',
                'fuel' => 'Gasolina',
                'transmission' => 'Manual',
                'price' => 40.00,
                'type' => 'Compacto',
                'image_1' => 'vehicles-photos/CITROEN_C3.png',
                'description' => 'Compacto urbano ideal para trayectos cortos y aparcamiento fácil.',
                'fee' => 120,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Mini',
                'model' => 'Cooper',
                'year' => 2021,
                'color' => 'Rojo',
                'fuel' => 'Gasolina',
                'transmission' => 'Manual',
                'price' => 59.00,
                'type' => 'Compacto',
                'image_1' => 'vehicles-photos/MINI_COOPER.png',
                'description' => 'Estilo clásico con conducción divertida y urbana.',
                'fee' => 175,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Peugeot',
                'model' => '408',
                'year' => 2023,
                'color' => 'Blanco',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 69.00,
                'type' => 'Sedán',
                'image_1' => 'vehicles-photos/PEUGEOT_408.png',
                'description' => 'Diseño moderno y gran eficiencia para el día a día.',
                'fee' => 210,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Peugeot',
                'model' => '408 SW',
                'year' => 2023,
                'color' => 'Gris grafito',
                'fuel' => 'Diésel',
                'transmission' => 'Automático',
                'price' => 72.00,
                'type' => 'Familiar',
                'image_1' => 'vehicles-photos/PEUGEOT_408_SW.png',
                'description' => 'Versión familiar con amplio maletero y diseño dinámico.',
                'fee' => 215,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],          
            [
                'brand' => 'Volkswagen',
                'model' => 'Caravelle',
                'year' => 2021,
                'color' => 'Negro',
                'fuel' => 'Diésel',
                'transmission' => 'Manual',
                'price' => 75.00,
                'type' => 'Furgoneta',
                'image_1' => 'vehicles-photos/VOLKSWAGEN_CARAVELLE.png',
                'description' => 'Amplia furgoneta ideal para grupos o familias numerosas.',
                'fee' => 230,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Aston Martin',
                'model' => 'DB12',
                'year' => 2024,
                'color' => 'Negro',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 340.00,
                'type' => 'Deportivo',
                'image_1' => 'vehicles-photos/ASTON_MARTIN_DB12_BLACK_2024.png',
                'description' => 'Coupé británico de lujo con gran carácter y potencia.',
                'fee' => 1100,
                'typeWarranty' => 'Exclusive',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Aston Martin',
                'model' => 'DBX',
                'year' => 2024,
                'color' => 'Plateado',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 310.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/ASTON_MARTIN_DBX_SILVER_2024.png',
                'description' => 'SUV de lujo con el alma de un deportivo.',
                'fee' => 1050,
                'typeWarranty' => 'Exclusive',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Maserati',
                'model' => 'Grecale',
                'year' => 2023,
                'color' => 'Azul',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 260.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/MASERATI_GRECALE_BLUE_2023.png',
                'description' => 'SUV italiano con elegancia y rendimiento deportivo.',
                'fee' => 850,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Mini',
                'model' => 'Cooper',
                'year' => 2024,
                'color' => 'Azul',
                'fuel' => 'Gasolina',
                'transmission' => 'Manual',
                'price' => 62.00,
                'type' => 'Compacto',
                'image_1' => 'vehicles-photos/MINI_COOPER_BLUE_2024.png',
                'description' => 'Un clásico moderno, ideal para la ciudad.',
                'fee' => 190,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'model' => '911 Carrera',
                'year' => 2024,
                'color' => 'Azul',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 310.00,
                'type' => 'Deportivo',
                'image_1' => 'vehicles-photos/PORSCHE_911_CARRERA_BLUE_2024.png',
                'description' => 'Símbolo de velocidad, precisión y clase.',
                'fee' => 999,
                'typeWarranty' => 'Exclusive',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'model' => '911 Carrera',
                'year' => 2019,
                'color' => 'Plateado',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 275.00,
                'type' => 'Deportivo',
                'image_1' => 'vehicles-photos/PORSCHE_911_CARRERA_SILVER_2019.png',
                'description' => 'Deportivo clásico con alma moderna.',
                'fee' => 870,
                'typeWarranty' => 'Estándar',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'model' => '911 Coupe',
                'year' => 2022,
                'color' => 'Gris',
                'fuel' => 'Gasolina',
                'transmission' => 'Manual',
                'price' => 298.00,
                'type' => 'Deportivo',
                'image_1' => 'vehicles-photos/PORSCHE_911_COUPE_GREY_2022.png',
                'description' => 'Estética deportiva refinada con conducción pura.',
                'fee' => 960,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'model' => 'Cayenne Coupe',
                'year' => 2024,
                'color' => 'Blanco',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 220.00,
                'type' => 'SUV',
                'image_1' => 'vehicles-photos/PORSCHE_CAYENNE_WHITE_2024.png',
                'description' => 'Deportivo y práctico: el SUV con alma Porsche.',
                'fee' => 720,
                'typeWarranty' => 'Premium',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'model' => 'Panamera',
                'year' => 2021,
                'color' => 'Negro',
                'fuel' => 'Gasolina',
                'transmission' => 'Automático',
                'price' => 270.00,
                'type' => 'Sedán',
                'image_1' => 'vehicles-photos/PORSCHE_PANAMERA_BLACK_2021.png',
                'description' => 'Sedán deportivo con confort de primera clase.',
                'fee' => 850,
                'typeWarranty' => 'Exclusive',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'model' => 'Taycan S',
                'year' => 2021,
                'color' => 'Plateado',
                'fuel' => 'Eléctrico',
                'transmission' => 'Automático',
                'price' => 320.00,
                'type' => 'Deportivo',
                'image_1' => 'vehicles-photos/PORSCHE_TAYCAN_SILVER_2021.png',
                'description' => 'Eléctrico con alma de pura velocidad.',
                'fee' => 980,
                'typeWarranty' => 'Exclusive',
                'published' => true,
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('vehicles')->insert($vehicles);
    }
}